services:
  # Servicio de Backend
  - type: web
    name: tpi-back
    env: docker
    fromRepo: true # <-- MEJORA: Usa el repo actual automáticamente
    branch: main
    dockerfilePath: ./back/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: database
          name: tpi-mysql-db
          property: connectionString # Render provee la URL de conexión completa
      - key: DB_HOST
        fromService:
          type: database
          name: tpi-mysql-db
          property: host
      - key: DB_PORT
        fromService:
          type: database
          name: tpi-mysql-db
          property: port

  # Servicio de Frontend
  - type: web
    name: tpi-front
    env: docker
    fromRepo: true # <-- MEJORA: Usa el repo actual automáticamente
    branch: main
    dockerfilePath: ./front/Dockerfile
    envVars:
      - key: __API_BASE__
        fromService:
          type: web
          name: tpi-back
          property: url
