name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  REGISTRY: docker.io
  USERNAME: franperrone

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Cambiá la versión si usás otra
      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      #- name: Ejecutar tests
      #  run: |
      #    source venv/bin/activate
      #    pytest

      
      

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Validar estructura del frontend
        run: |
         echo "Archivos en front/"
          ls -la


  #  Etapa para completar: build y push a Docker Hub
  docker-publish:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # TODO: Agregar login y docker build/push
      - name: Placeholder para build y push
        run: echo "Acá va el docker build y push a Docker Hub"